In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

In [2]:
iris = load_iris()

In [3]:
X = iris.data[:, :] # Petal length and width
y = iris.target

In [4]:
tree_clf = DecisionTreeClassifier(max_depth=4)

In [5]:
tree_clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [6]:
iris.feature_names[2:]

['petal length (cm)', 'petal width (cm)']

In [7]:
from sklearn.tree import export_graphviz

In [8]:
export_graphviz(
    tree_clf,
    out_file="iris_tree.dot",
    feature_names = iris.feature_names[:],
    class_names = iris.target_names,
    rounded = True,
    filled = True
)

<img src="iris_tree1.png">

In [9]:
iris.target == tree_clf.predict(iris.data)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

## MNIST Classification using Decision Tree Classifier

In [10]:
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
learn = tf.contrib.learn
tf.logging.set_verbosity(tf.logging.ERROR)

/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)


In [11]:
mnist = learn.datasets.load_dataset('mnist')
data = mnist.train.images
labels = np.asarray(mnist.train.labels, dtype=np.int32)
test_data = mnist.test.images
test_labels = np.asarray(mnist.test.labels, dtype=np.int32)

Extracting MNIST-data/train-images-idx3-ubyte.gz
Extracting MNIST-data/train-labels-idx1-ubyte.gz
Extracting MNIST-data/t10k-images-idx3-ubyte.gz
Extracting MNIST-data/t10k-labels-idx1-ubyte.gz


In [12]:
max_examples = 80000
data = data[:max_examples]
labels = labels[:max_examples]

test_data = test_data[:]
test_labels = test_labels[:]
# 
# print(len(test_data))

In [13]:
tree_clf1 = DecisionTreeClassifier(max_depth=10)

In [14]:
tree_clf1.fit(data, labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [15]:
output = tree_clf1.predict(test_data)

In [16]:
accuaracy = test_labels == output

In [17]:
i = 0
for _ in accuaracy:
    if _:
        i = i+1
i

8657

In [18]:
mnist_class_names = np.arange(10).astype(str)
mnist_class_names

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

In [19]:
export_graphviz(
    tree_clf1,
    out_file="mnist_tree.dot",
    class_names = mnist_class_names,
    rounded = True,
    filled = True
)

<img src="mnist_tree.png">

In [20]:
tree_clf1.predict_proba([test_data[0]])

array([[2.29568411e-04, 4.13223140e-03, 5.28007346e-03, 5.05050505e-03,
        2.29568411e-03, 1.14784206e-03, 1.14784206e-03, 9.69696970e-01,
        9.18273646e-04, 1.01010101e-02]])

In [32]:
tree_clf1.predict([test_data[7]])

array([7], dtype=int32)

In [35]:
test_data[7]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [76]:
img = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.578125,0.97265625,0.984375,0.984375,0.98828125,0.98046875,0.9609375,0.97265625,0.9609375,0.9609375,0.97265625,0.98046875,0.9765625,0.734375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.09765625,0.27734375,0.33984375,0.33984375,0.37109375,0.3046875,0.2421875,0.27734375,0.2421875,0.2421875,0.27734375,0.87890625,0.90625,0.08984375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.77734375,0.81640625,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.73828125,0.8203125,0.05078125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.8046875,0.8046875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.6015625,0.9609375,0.68359375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.875,0.8828125,0.05078125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.8515625,0.87890625,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.828125,0.88671875,0.09375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.87890625,0.875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.87890625,0.875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.87890625,0.875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.87890625,0.875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.87890625,0.875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.8046875,0.97265625,0.59765625,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.09765625,0.88671875,0.87109375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.703125,0.69921875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.05078125,0.05078125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]





In [77]:
img = np.asarray(img)

In [100]:
tree_clf1.predict([img])

array([2], dtype=int32)

In [101]:
import pickle

In [102]:
pickle.dumps(tree_clf1)

b'\x80\x03csklearn.tree.tree\nDecisionTreeClassifier\nq\x00)\x81q\x01}q\x02(X\t\x00\x00\x00criterionq\x03X\x04\x00\x00\x00giniq\x04X\x08\x00\x00\x00splitterq\x05X\x04\x00\x00\x00bestq\x06X\t\x00\x00\x00max_depthq\x07K\nX\x11\x00\x00\x00min_samples_splitq\x08K\x02X\x10\x00\x00\x00min_samples_leafq\tK\x01X\x18\x00\x00\x00min_weight_fraction_leafq\nG\x00\x00\x00\x00\x00\x00\x00\x00X\x0c\x00\x00\x00max_featuresq\x0bNX\x0c\x00\x00\x00random_stateq\x0cNX\x0e\x00\x00\x00max_leaf_nodesq\rNX\x15\x00\x00\x00min_impurity_decreaseq\x0eG\x00\x00\x00\x00\x00\x00\x00\x00X\x12\x00\x00\x00min_impurity_splitq\x0fNX\x0c\x00\x00\x00class_weightq\x10NX\x07\x00\x00\x00presortq\x11\x89X\x0b\x00\x00\x00n_features_q\x12M\x10\x03X\n\x00\x00\x00n_outputs_q\x13K\x01X\x08\x00\x00\x00classes_q\x14cnumpy.core.multiarray\n_reconstruct\nq\x15cnumpy\nndarray\nq\x16K\x00\x85q\x17C\x01bq\x18\x87q\x19Rq\x1a(K\x01K\n\x85q\x1bcnumpy\ndtype\nq\x1cX\x02\x00\x00\x00i4q\x1dK\x00K\x01\x87q\x1eRq\x1f(K\x03X\x01\x00\x00\x00<q NNNJ

In [103]:
f = open('weights_dtc','wb')

In [104]:
f.write(s)

235374

In [105]:
fr = open('weights_dtc', 'rb')

In [106]:
binn = fr.read()

In [107]:
new_clf = pickle.loads(binn)

In [108]:
tree_clf1.predict([img])

array([2], dtype=int32)

In [109]:
new_clf.predict([img])

array([2], dtype=int32)