In [299]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [300]:
dataset1 = pd.read_csv("datasets/Data.csv")

In [301]:
dataset1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [302]:
X = dataset1.iloc[:, 0:3].values

In [303]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [304]:
y = dataset1.iloc[:, -1].values

In [305]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [306]:
from sklearn.impute import SimpleImputer

In [307]:
sim = SimpleImputer()

In [308]:
sim

SimpleImputer(copy=True, fill_value=None, missing_values=nan, strategy='mean',
       verbose=0)

In [309]:
sim.fit(X[:, 1:3])
sim.transform(X[:, 1:3])

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [310]:
X[:, 1:3] = sim.transform(X[:, 1:3])

In [311]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [312]:
from sklearn.preprocessing import LabelEncoder

In [313]:
lab = LabelEncoder()

In [314]:
X[:, 0] = lab.fit_transform(X[:, 0])

In [315]:
lab.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [316]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [317]:
from sklearn.preprocessing import OneHotEncoder

In [318]:
X = one.fit_transform(X)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


IndexError: index 3 is out of bounds for axis 1 with size 3

In [319]:
one = OneHotEncoder(categorical_features=[0])

In [320]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [321]:
X = X.toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [322]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [323]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [324]:
y = lab.fit_transform(y)

In [325]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [326]:
from sklearn.preprocessing import StandardScaler

In [327]:
ss = StandardScaler()

In [328]:
ss.fit_transform(X)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.08347268e+00,  7.58874362e-01,  7.49473254e-01],
       [ 1.32424438e+00, -1.71150388e+00, -1.43817841e+00],
       [ 1.20385853e-01, -1.27555478e+00, -8.91265492e-01],
       [ 1.32424438e+00, -1.13023841e-01, -2.53200424e-01],
       [ 1.20385853e-01,  1.77608893e-01,  6.63219199e-16],
       [-1.08347268e+00, -5.48972942e-01, -5.26656882e-01],
       [ 1.32424438e+00,  0.00000000e+00, -1.07356980e+00],
       [-1.08347268e+00,  1.34013983e+00,  1.38753832e+00],
       [ 1.20385853e-01,  1.63077256e+00,  1.75214693e+00],
       [-1.08347268e+00, -2.58340208e-01,  2.93712492e-01]])

In [329]:
dataset2 = pd.read_csv('datasets/adult.csv', na_values=" ?")

In [330]:
dataset2

39          State-gov   77516      Bachelors   13  \
0      50   Self-emp-not-inc   83311      Bachelors   13   
1      38            Private  215646        HS-grad    9   
2      53            Private  234721           11th    7   
3      28            Private  338409      Bachelors   13   
4      37            Private  284582        Masters   14   
5      49            Private  160187            9th    5   
6      52   Self-emp-not-inc  209642        HS-grad    9   
7      31            Private   45781        Masters   14   
8      42            Private  159449      Bachelors   13   
9      37            Private  280464   Some-college   10   
10     30          State-gov  141297      Bachelors   13   
11     23            Private  122272      Bachelors   13   
12     32            Private  205019     Assoc-acdm   12   
13     40            Private  121772      Assoc-voc   11   
14     34            Private  245487        7th-8th    4   
15     25   Self-emp-not-inc  176756        HS-grad    9   
16     32            Private  186824        HS-grad    9   
17     38            Private   28887           11th    7   
18     43   Self-emp-not-inc  292175        Masters   14   
19     40            Private  193524      Doctorate   16   
20     54            Private  302146        HS-grad    9   
21     35        Federal-gov   76845            9th    5   
22     43            Private  117037           11th    7   
23     59            Private  109015        HS-grad    9   
24     56          Local-gov  216851      Bachelors   13   
25     19            Private  168294        HS-grad    9   
26     54                NaN  180211   Some-college   10   
27     39            Private  367260        HS-grad    9   
28     49            Private  193366        HS-grad    9   
29     23          Local-gov  190709     Assoc-acdm   12   
...    ..                ...     ...            ...  ...   
32530  30                NaN   33811      Bachelors   13   
32531  34            Private  204461      Doctorate   16   
32532  54            Private  337992      Bachelors   13   
32533  37            Private  179137   Some-college   10   
32534  22            Private  325033           12th    8   
32535  34            Private  160216      Bachelors   13   
32536  30            Private  345898        HS-grad    9   
32537  38            Private  139180      Bachelors   13   
32538  71                NaN  287372      Doctorate   16   
32539  45          State-gov  252208        HS-grad    9   
32540  41                NaN  202822        HS-grad    9   
32541  72                NaN  129912        HS-grad    9   
32542  45          Local-gov  119199     Assoc-acdm   12   
32543  31            Private  199655        Masters   14   
32544  39          Local-gov  111499     Assoc-acdm   12   
32545  37            Private  198216     Assoc-acdm   12   
32546  43            Private  260761        HS-grad    9   
32547  65   Self-emp-not-inc   99359    Prof-school   15   
32548  43          State-gov  255835   Some-college   10   
32549  43   Self-emp-not-inc   27242   Some-college   10   
32550  32            Private   34066           10th    6   
32551  43            Private   84661      Assoc-voc   11   
32552  32            Private  116138        Masters   14   
32553  53            Private  321865        Masters   14   
32554  22            Private  310152   Some-college   10   
32555  27            Private  257302     Assoc-acdm   12   
32556  40            Private  154374        HS-grad    9   
32557  58            Private  151910        HS-grad    9   
32558  22            Private  201490        HS-grad    9   
32559  52       Self-emp-inc  287927        HS-grad    9   

                Never-married        Adm-clerical    Not-in-family  \
0          Married-civ-spouse     Exec-managerial          Husband   
1                    Divorced   Handlers-cleaners    Not-in-family   
2          Married-civ-spouse   Handlers-cleaners          Husband   
3     

In [331]:
X = dataset2.iloc[:, 0:14].values
y = dataset2.iloc[:, -1].values

In [332]:
X

array([[50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       [53, ' Private', 234721, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [333]:
y

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [334]:
sim = SimpleImputer()

In [335]:
X[:, [0,2,4,10,11,12]] = sim.fit_transform(X[:, [0,2,4,10,11,12]])

In [336]:
temp = pd.DataFrame(X[:, [1,3,5,6,7,8,9,13]])

In [337]:
temp

0              1                       2  \
0       Self-emp-not-inc      Bachelors      Married-civ-spouse   
1                Private        HS-grad                Divorced   
2                Private           11th      Married-civ-spouse   
3                Private      Bachelors      Married-civ-spouse   
4                Private        Masters      Married-civ-spouse   
5                Private            9th   Married-spouse-absent   
6       Self-emp-not-inc        HS-grad      Married-civ-spouse   
7                Private        Masters           Never-married   
8                Private      Bachelors      Married-civ-spouse   
9                Private   Some-college      Married-civ-spouse   
10             State-gov      Bachelors      Married-civ-spouse   
11               Private      Bachelors           Never-married   
12               Private     Assoc-acdm           Never-married   
13               Private      Assoc-voc      Married-civ-spouse   
14               Private        7th-8th      Married-civ-spouse   
15      Self-emp-not-inc        HS-grad           Never-married   
16               Private        HS-grad           Never-married   
17               Private           11th      Married-civ-spouse   
18      Self-emp-not-inc        Masters                Divorced   
19               Private      Doctorate      Married-civ-spouse   
20               Private        HS-grad               Separated   
21           Federal-gov            9th      Married-civ-spouse   
22               Private           11th      Married-civ-spouse   
23               Private        HS-grad                Divorced   
24             Local-gov      Bachelors      Married-civ-spouse   
25               Private        HS-grad           Never-married   
26                   NaN   Some-college      Married-civ-spouse   
27               Private        HS-grad                Divorced   
28               Private        HS-grad      Married-civ-spouse   
29             Local-gov     Assoc-acdm           Never-married   
...                  ...            ...                     ...   
32530                NaN      Bachelors           Never-married   
32531            Private      Doctorate      Married-civ-spouse   
32532            Private      Bachelors      Married-civ-spouse   
32533            Private   Some-college                Divorced   
32534            Private           12th           Never-married   
32535            Private      Bachelors           Never-married   
32536            Private        HS-grad           Never-married   
32537            Private      Bachelors                Divorced   
32538                NaN      Doctorate      Married-civ-spouse   
32539          State-gov        HS-grad               Separated   
32540                NaN        HS-grad               Separated   
32541                NaN        HS-grad      Married-civ-spouse   
32542          Local-gov     Assoc-acdm                Divorced   
32543            Private        Masters                Divorced   
32544          Local-gov     Assoc-acdm      Married-civ-spouse   
32545            Private     Assoc-acdm                Divorced   
32546            Private        HS-grad      Married-civ-spouse   
32547   Self-emp-not-inc    Prof-school           Never-married   
32548          State-gov   Some-college                Divorced   
32549   Self-emp-not-inc   Some-college      Married-civ-spouse   
32550            Private           10th      Married-civ-spouse   
32551            Private      Assoc-voc      Married-civ-spouse   
32552            Private        Masters           Never-married   
32553            Private        Masters      Married-civ-spouse   
32554            Private   Some-college           Never-married   
32555            Private     Assoc-acdm      Married-civ-spouse   
32556            Private        HS-grad      Married-civ-spouse   
32557            Private        HS-grad                 Widowed   
325

In [338]:
temp[0].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: 0, dtype: int64

In [339]:
temp[1].value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: 1, dtype: int64

In [340]:
temp[2].value_counts()

 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: 2, dtype: int64

In [341]:
temp[3].value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3769
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: 3, dtype: int64

In [342]:
temp[4].value_counts()

 Husband           13193
 Not-in-family      8304
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: 4, dtype: int64

In [343]:
temp[5].value_counts()

 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: 5, dtype: int64

In [344]:
temp[6].value_counts()

 Male      21789
 Female    10771
Name: 6, dtype: int64

In [345]:
temp[7].value_counts()

 United-States                 29169
 Mexico                          643
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 Greece                           29
 

In [346]:
temp[0] = temp[0].fillna(' Private')
# temp[1] = temp[1].fillna('  HS-grad')


In [347]:
temp[0].value_counts()

 Private             24532
 Self-emp-not-inc     2541
 Local-gov            2093
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: 0, dtype: int64

In [348]:
temp[1] = temp[1].fillna(' HS-grad')

In [349]:
temp[1].value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: 1, dtype: int64

In [350]:
temp[2] = temp[2].fillna(' Married-civ-spouse')

In [351]:
temp[2].value_counts()

 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: 2, dtype: int64

In [352]:
temp[3] = temp[3].fillna(' Prof-specialty')
temp[3].value_counts()

 Prof-specialty       5983
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3769
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: 3, dtype: int64

In [353]:
temp[4] = temp[4].fillna(' Husband')
temp[4].value_counts()

 Husband           13193
 Not-in-family      8304
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: 4, dtype: int64

In [354]:
temp[5] = temp[5].fillna(' White')
temp[5].value_counts()

 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: 5, dtype: int64

In [355]:
temp[6] = temp[6].fillna(' Male')
temp[6].value_counts()

 Male      21789
 Female    10771
Name: 6, dtype: int64

In [356]:
temp[7] = temp[7].fillna(' United-States')
temp[7].value_counts()

 United-States                 29752
 Mexico                          643
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 Greece                           29
 

In [357]:
X[:, [1,3,5,6,7,8,9,13]] = temp

In [358]:
from sklearn.preprocessing import LabelEncoder

In [359]:
lab = LabelEncoder()

In [360]:
X[:, 1]

array([' Self-emp-not-inc', ' Private', ' Private', ..., ' Private',
       ' Private', ' Self-emp-inc'], dtype=object)

In [361]:
X[:, 1] = lab.fit_transform(X[:, 1])

In [362]:
X[:, 1]

array([5, 3, 3, ..., 3, 3, 4], dtype=object)

In [363]:
X[:, 3] = lab.fit_transform(X[:, 3])

In [364]:
X[:, 5] = lab.fit_transform(X[:, 5])
X[:, 6] = lab.fit_transform(X[:, 6])
X[:, 7] = lab.fit_transform(X[:, 7])
X[:, 8] = lab.fit_transform(X[:, 8])
X[:, 9] = lab.fit_transform(X[:, 9])
X[:, 13] = lab.fit_transform(X[:, 13])

In [365]:
X

array([[50.0, 5, 83311.0, ..., 0.0, 13.0, 38],
       [38.0, 3, 215646.0, ..., 0.0, 40.0, 38],
       [53.0, 3, 234721.0, ..., 0.0, 40.0, 38],
       ...,
       [58.0, 3, 151910.0, ..., 0.0, 40.0, 38],
       [22.0, 3, 201490.0, ..., 0.0, 20.0, 38],
       [52.0, 4, 287927.0, ..., 0.0, 40.0, 38]], dtype=object)

In [366]:
from sklearn.preprocessing import OneHotEncoder

In [367]:
one = OneHotEncoder(categorical_features=[1, 3, 5, 6, 7, 8, 9, 13])

In [368]:
X = one.fit_transform(X)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [369]:
X = X.toarray()

In [376]:
y = lab.fit_transform(y)

In [377]:
y

array([0, 0, 0, ..., 0, 0, 1])

In [378]:
lab.classes_

array([' <=50K', ' >50K'], dtype=object)