In [1]:
import numpy as np

## Array Creation

In [44]:
arr = np.arange(10,dtype=np.int)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Convert type of array

In [46]:
arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.float_(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
for i in arr:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [55]:
np.append(arr, [10])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr1 = [1,2,3,4,5,6,7,8,9,10]

In [57]:
arr1.append(11)

In [58]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.array(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [92]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
np.ones([3,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(0,101, 5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [110]:
np.linspace(1,100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Array Indexing
<hr>
<br>


In [144]:
arr = np.arange(10)

In [145]:
print(arr[8])
print(arr[2:5])

8
[2 3 4]


In [146]:
arr[-7]

3

In [147]:
arr[1:-7]

array([1, 2])

In [148]:
arr1 = np.arange(9)

In [149]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [153]:
# arr1 = arr1.reshape(3,3) # or 
arr1.shape = (3,3)

In [154]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
arr1[0,1]

1

### Index Array

In [159]:
arr = np.arange(10, 100)

In [160]:
arr[np.array([1,5,3,4])]

array([11, 15, 13, 14])

In [161]:
b = arr>50

In [162]:
b

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

## Broadcasting

In [163]:
a = np.arange(1,11)

In [172]:
b = np.arange(11,21)

In [173]:
a+b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [174]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [176]:
x = np.arange(4)

In [177]:
xx = x.reshape(4,1)

In [178]:
x

array([0, 1, 2, 3])

In [179]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [181]:
y = np.ones(5)

In [182]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [183]:
y

array([1., 1., 1., 1., 1.])

In [184]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [196]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])