In [1]:
import numpy as np
import pandas as  pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)


In [3]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [4]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)
total = a + b

In [5]:
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [7]:
writer = tf.summary.FileWriter('log')
writer.add_graph(tf.get_default_graph())
writer.flush()

In [8]:
!tensorboard --logdir ./log

/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
TensorBoard 1.12.1 at http://VISHALs-MacBook-Pro.local:6006 (Press CTRL+C to quit)
^C


In [10]:
sess = tf.Session()
print(sess.run(total))

7.0


In [11]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2

print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.58169997 0.35114658 0.69087565]
[0.4609753 0.4474094 0.580078 ]
(array([1.8981692, 1.9072772, 1.3917267], dtype=float32), array([2.898169 , 2.907277 , 2.3917267], dtype=float32))


In [12]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [13]:
print(sess.run(z, feed_dict={x: 3, y: 4}))

7.0


In [14]:
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

[3. 7.]


In [15]:
writer = tf.summary.FileWriter('log')
writer.add_graph(tf.get_default_graph())
writer.flush()

In [16]:
my_data = [
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
    [8, 9],
]

In [17]:
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [18]:
while True:
    try:
        print(sess.run(next_item))
    except tf.errors.OutOfRangeError:
        break
        

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [19]:
writer = tf.summary.FileWriter('log')
writer.add_graph(tf.get_default_graph())
writer.flush()

In [122]:
r = tf.random_normal([10, 3])

In [124]:
dataset = tf.data.Dataset.from_tensor_slices(r)


In [125]:
iterator = dataset.make_initializable_iterator()

In [126]:
next_row = iterator.get_next()

In [127]:
sess.run(iterator.initializer)

In [128]:
while True:
    try:
        print(sess.run(next_row))
    except tf.errors.OutOfRangeError:
        break
        

[ 0.60401064 -0.02549048 -0.65321404]
[-0.03527313 -1.4843142   0.15342472]
[-1.2104806 -1.2956172  1.2914277]
[-0.35729352  0.31579307  0.77952355]
[-0.01097706 -0.37257314 -2.0868275 ]
[0.4152729  0.48226964 0.73459333]
[-0.12180974  1.4113609  -1.2685875 ]
[-0.87900996 -1.2609608  -0.10215944]
[-0.434146   -1.2652956  -0.72773033]
[ 1.0653042 -1.6727417 -0.3304544]


In [141]:
x = tf.placeholder(tf.float32, shape=[None, 3])

In [142]:
print(x)

Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)


In [143]:
linear_model = tf.layers.Dense(units=1)

In [144]:
print(linear_model)

In [145]:
y = linear_model(x)

In [146]:
y

<tf.Tensor 'dense/BiasAdd:0' shape=(?, 1) dtype=float32>

In [147]:
init  = tf.global_variables_initializer()

In [148]:
sess.run(init)

In [149]:
print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[3.6708088]
 [8.4294815]]
